x-environment: &environment
  TZ: Asia/Tokyo

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - bundle:/usr/local/bundle
      - ./.aliases:/root/.aliases
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      <<: *environment
      RAILS_ENV: ${RAILS_ENV}
      DATABASE_HOST: ${DATABASE_HOST}
    command: bash -c "source ~/.bashrc && bundle exec rails s -b '0.0.0.0'"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - "3001:3000"
    environment:
      <<: *environment
      NODE_ENV: ${NODE_ENV}
    command: npm run dev
    working_dir: /usr/src/app

  db:
    container_name: db
    image: postgres:16.4
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      <<: *environment
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  bundle:
  node_modules:
